codeunit 54060 "SI BP Projection Mgt."
{
    procedure ProjectionExists(
        RoleCode: Code[30]): Boolean
    var
        Projection: Record "SI BP ERP Projection";
    begin
        exit(
            Projection.Get(RoleCode));
    end;

    procedure CreateProjection(
        Role: Record "SI BP Role";
        var Projection: Record "SI BP ERP Projection")
    var
        BusinessPartner: Record "SI Business Partner";
    begin
        Role.TestField(Code);

        if Role.Status <> Role.Status::Active then
            Error(
                'ERP-проєкцію можна створити лише для активної ролі.');

        if Projection.Get(Role.Code) then
            Error(
                'Для ролі %1 ERP-проєкція вже існує.',
                Role.Code);

        BusinessPartner.Get(
            Role."Business Partner No.");

        Projection.Init();

        Projection."Role Code" :=
            Role.Code;

        Projection."Business Partner No." :=
            Role."Business Partner No.";

        Projection."Business Partner Name" :=
            CopyStr(
                BusinessPartner.Name,
                1,
                MaxStrLen(
                    Projection."Business Partner Name"));

        Projection."Role Type" :=
            Role."Role Type";

        Projection.Name :=
            CopyStr(
                BusinessPartner.Name,
                1,
                MaxStrLen(Projection.Name));

        Projection."Country/Region Code" :=
            BusinessPartner."Country/Region Code";

        Projection."Currency Code" :=
            BusinessPartner."Currency Code";

        Projection."Registration No." :=
            CopyStr(
                BusinessPartner."Registration No.",
                1,
                MaxStrLen(
                    Projection."Registration No."));

        Projection."Tax Registration No." :=
            CopyStr(
                BusinessPartner."Tax Registration No.",
                1,
                MaxStrLen(
                    Projection."Tax Registration No."));

        FillLegalAddress(
            BusinessPartner,
            Projection);


        Projection.Status :=
            Projection.Status::Ready;

        Projection."Generated At" :=
            CurrentDateTime;

        Projection."Generated By" :=
            CopyStr(
                UserId(),
                1,
                MaxStrLen(
                    Projection."Generated By"));

        Projection.Insert(true);

        CreateBankProjectionLines(
            Role,
            Projection);

        ValidateProjection(
            Projection);
    end;

    procedure ValidateProjection(
        var Projection: Record "SI BP ERP Projection")
    var
        ProjectionBank: Record "SI BP ERP Proj. Bank";
        ErrorText: Text;
    begin
        ErrorText := '';

        if Projection.Name = '' then
            AddError(
                ErrorText,
                'Не зазначено назву контрагента.');

        if Projection."Country/Region Code" = '' then
            AddError(
                ErrorText,
                'Не зазначено країну юридичної адреси.');

        if Projection."Address City" = '' then
            AddError(
                ErrorText,
                'Не зазначено місто юридичної адреси.');

        if Projection."Address Street" = '' then
            AddError(
                ErrorText,
                'Не зазначено вулицю юридичної адреси.');

        ProjectionBank.SetRange(
            "Role Code",
            Projection."Role Code");

        if ProjectionBank.IsEmpty() then
            AddError(
                ErrorText,
                'Проєкція не містить перевірених банківських рахунків.');

        Projection."Validated At" :=
            CurrentDateTime;

        Projection."Error Message" :=
            CopyStr(
                ErrorText,
                1,
                MaxStrLen(
                    Projection."Error Message"));

        if ErrorText = '' then
            Projection.Status :=
                Projection.Status::Ready
        else
            Projection.Status :=
                Projection.Status::Error;

        Projection.Modify(true);
    end;

    procedure DeleteProjection(
        RoleCode: Code[30])
    var
        Projection: Record "SI BP ERP Projection";
    begin
        if not Projection.Get(RoleCode) then
            Error(
                'ERP-проєкцію ролі %1 не знайдено.',
                RoleCode);

        if Projection.Status =
           Projection.Status::Materialized
        then
            Error(
                'Матеріалізовану ERP-проєкцію видаляти не можна.');

        Projection.Delete(true);
    end;

    procedure MaterializeProjection(
        var Projection: Record "SI BP ERP Projection")
    begin
        Projection.Get(
            Projection."Role Code");

        if Projection.Status =
           Projection.Status::Materialized
        then
            Error(
                'ERP-проєкція вже матеріалізована.');

        if Projection.Status <>
           Projection.Status::Ready
        then
            Error(
                'Матеріалізувати можна лише проєкцію зі станом Готова.');

        case Projection."Role Type" of
            Projection."Role Type"::Vendor:
                MaterializeVendor(
                    Projection);

            Projection."Role Type"::Customer:
                MaterializeCustomer(
                    Projection);
        end;
    end;

    local procedure MaterializeVendor(
        var Projection: Record "SI BP ERP Projection")
    var
        Role: Record "SI BP Role";
        Vendor: Record Vendor;
    begin
        Role.Get(
            Projection."Role Code");

        if Role.Status <> Role.Status::Active then
            Error(
                'Матеріалізувати ERP-проєкцію можна лише для активної ролі.');

        if Role."Vendor No." <> '' then
            Error(
                'Роль %1 уже пов''язана з постачальником %2.',
                Role.Code,
                Role."Vendor No.");

        Vendor.Init();
        Vendor.Insert(true);

        Vendor.Validate(
            Name,
            CopyStr(
                Projection.Name,
                1,
                MaxStrLen(Vendor.Name)));

        if Projection."Country/Region Code" <> '' then
            Vendor.Validate(
                "Country/Region Code",
                Projection."Country/Region Code");

        ApplyVendorAddress(
            Projection,
            Vendor);

        if Projection."Tax Registration No." <> '' then
            Vendor.Validate(
                "VAT Registration No.",
                CopyStr(
                    Projection."Tax Registration No.",
                    1,
                    MaxStrLen(
                        Vendor."VAT Registration No.")));

        Vendor.Modify(true);

        MaterializeVendorBanks(
            Projection,
            Vendor);

        Role."Vendor No." :=
            Vendor."No.";

        Role.Modify(true);

        CompleteMaterialization(
            Projection,
            Vendor."No.",
            Vendor.SystemId);
    end;

    local procedure MaterializeCustomer(
        var Projection: Record "SI BP ERP Projection")
    var
        Role: Record "SI BP Role";
        Customer: Record Customer;
    begin
        Role.Get(
            Projection."Role Code");

        if Role.Status <> Role.Status::Active then
            Error(
                'Матеріалізувати ERP-проєкцію можна лише для активної ролі.');

        if Role."Customer No." <> '' then
            Error(
                'Роль %1 уже пов''язана з покупцем %2.',
                Role.Code,
                Role."Customer No.");

        Customer.Init();
        Customer.Insert(true);

        Customer.Validate(
            Name,
            CopyStr(
                Projection.Name,
                1,
                MaxStrLen(Customer.Name)));

        if Projection."Country/Region Code" <> '' then
            Customer.Validate(
                "Country/Region Code",
                Projection."Country/Region Code");

        ApplyCustomerAddress(
            Projection,
            Customer);

        if Projection."Tax Registration No." <> '' then
            Customer.Validate(
                "VAT Registration No.",
                CopyStr(
                    Projection."Tax Registration No.",
                    1,
                    MaxStrLen(
                        Customer."VAT Registration No.")));

        Customer.Modify(true);

        MaterializeCustomerBanks(
            Projection,
            Customer);

        Role."Customer No." :=
            Customer."No.";

        Role.Modify(true);

        CompleteMaterialization(
            Projection,
            Customer."No.",
            Customer.SystemId);
    end;

    local procedure CompleteMaterialization(
        var Projection: Record "SI BP ERP Projection";
        ERPNo: Code[20];
        ERPSystemId: Guid)
    begin
        Projection."ERP No." :=
            ERPNo;

        Projection."ERP SystemId" :=
            ERPSystemId;

        Projection.Status :=
            Projection.Status::Materialized;

        Projection."Materialized At" :=
            CurrentDateTime;

        Projection."Materialized By" :=
            CopyStr(
                UserId(),
                1,
                MaxStrLen(
                    Projection."Materialized By"));

        Projection.Modify(true);
    end;

    local procedure MaterializeVendorBanks(
        Projection: Record "SI BP ERP Projection";
        Vendor: Record Vendor)
    var
        ProjectionBank: Record "SI BP ERP Proj. Bank";
        VendorBankAccount: Record "Vendor Bank Account";
    begin
        ProjectionBank.SetRange(
            "Role Code",
            Projection."Role Code");

        if not ProjectionBank.FindSet() then
            exit;

        repeat
            VendorBankAccount.Init();

            VendorBankAccount."Vendor No." :=
                Vendor."No.";

            VendorBankAccount.Code :=
                ProjectionBank.Code;

            VendorBankAccount.Name :=
                CopyStr(
                    ProjectionBank."Bank Name",
                    1,
                    MaxStrLen(
                        VendorBankAccount.Name));

            VendorBankAccount."Bank Branch No." :=
                ProjectionBank.MFO;

            VendorBankAccount."Bank Account No." :=
                CopyStr(
                    ProjectionBank."Account No.",
                    1,
                    MaxStrLen(
                        VendorBankAccount."Bank Account No."));

            VendorBankAccount.IBAN :=
                CopyStr(
                    ProjectionBank.IBAN,
                    1,
                    MaxStrLen(
                        VendorBankAccount.IBAN));

            VendorBankAccount."Currency Code" :=
                ProjectionBank."Currency Code";

            VendorBankAccount."Country/Region Code" :=
                ProjectionBank."Country/Region Code";

            VendorBankAccount.Address :=
                CopyStr(
                    ProjectionBank."Bank Address",
                    1,
                    MaxStrLen(
                        VendorBankAccount.Address));

            VendorBankAccount.City :=
                CopyStr(
                    ProjectionBank."Bank City",
                    1,
                    MaxStrLen(
                        VendorBankAccount.City));

            VendorBankAccount."Post Code" :=
                CopyStr(
                    ProjectionBank."Bank Postal Code",
                    1,
                    MaxStrLen(
                        VendorBankAccount."Post Code"));

            VendorBankAccount."Phone No." :=
                CopyStr(
                    ProjectionBank."Bank Phone",
                    1,
                    MaxStrLen(
                        VendorBankAccount."Phone No."));

            VendorBankAccount.Insert(true);
        until ProjectionBank.Next() = 0;
    end;

    local procedure MaterializeCustomerBanks(
        Projection: Record "SI BP ERP Projection";
        Customer: Record Customer)
    var
        ProjectionBank: Record "SI BP ERP Proj. Bank";
        CustomerBankAccount: Record "Customer Bank Account";
    begin
        ProjectionBank.SetRange(
            "Role Code",
            Projection."Role Code");

        if not ProjectionBank.FindSet() then
            exit;

        repeat
            CustomerBankAccount.Init();

            CustomerBankAccount."Customer No." :=
                Customer."No.";

            CustomerBankAccount.Code :=
                ProjectionBank.Code;

            CustomerBankAccount.Name :=
                CopyStr(
                    ProjectionBank."Bank Name",
                    1,
                    MaxStrLen(
                        CustomerBankAccount.Name));

            CustomerBankAccount."Bank Branch No." :=
                ProjectionBank.MFO;

            CustomerBankAccount."Bank Account No." :=
                CopyStr(
                    ProjectionBank."Account No.",
                    1,
                    MaxStrLen(
                        CustomerBankAccount."Bank Account No."));

            CustomerBankAccount.IBAN :=
                CopyStr(
                    ProjectionBank.IBAN,
                    1,
                    MaxStrLen(
                        CustomerBankAccount.IBAN));

            CustomerBankAccount."Currency Code" :=
                ProjectionBank."Currency Code";

            CustomerBankAccount."Country/Region Code" :=
                ProjectionBank."Country/Region Code";

            CustomerBankAccount.Address :=
                CopyStr(
                    ProjectionBank."Bank Address",
                    1,
                    MaxStrLen(
                        CustomerBankAccount.Address));

            CustomerBankAccount.City :=
                CopyStr(
                    ProjectionBank."Bank City",
                    1,
                    MaxStrLen(
                        CustomerBankAccount.City));

            CustomerBankAccount."Post Code" :=
                CopyStr(
                    ProjectionBank."Bank Postal Code",
                    1,
                    MaxStrLen(
                        CustomerBankAccount."Post Code"));

            CustomerBankAccount."Phone No." :=
                CopyStr(
                    ProjectionBank."Bank Phone",
                    1,
                    MaxStrLen(
                        CustomerBankAccount."Phone No."));

            CustomerBankAccount.Insert(true);
        until ProjectionBank.Next() = 0;
    end;

    local procedure FillLegalAddress(
        BusinessPartner: Record "SI Business Partner";
        var Projection: Record "SI BP ERP Projection")
    var
        BPAddress: Record "SI BP Address";
    begin
        if not GetCurrentLegalAddress(
            BusinessPartner."No.",
            BPAddress)
        then
            exit;

        Projection."Country/Region Code" :=
            BPAddress."Country/Region Code";

        Projection."Address Region/State" :=
            CopyStr(
                BPAddress."Region/State",
                1,
                MaxStrLen(
                    Projection."Address Region/State"));

        Projection."Address District" :=
            CopyStr(
                BPAddress.District,
                1,
                MaxStrLen(
                    Projection."Address District"));

        Projection."Address City" :=
            CopyStr(
                BPAddress.City,
                1,
                MaxStrLen(
                    Projection."Address City"));

        Projection."Address Post Code" :=
            CopyStr(
                BPAddress."Post Code",
                1,
                MaxStrLen(
                    Projection."Address Post Code"));

        Projection."Address Street" :=
            CopyStr(
                BPAddress.Street,
                1,
                MaxStrLen(
                    Projection."Address Street"));

        Projection."Address Building No." :=
            CopyStr(
                BPAddress."Building No.",
                1,
                MaxStrLen(
                    Projection."Address Building No."));

        Projection."Address Office/Apartment" :=
            CopyStr(
                BPAddress."Office/Apartment",
                1,
                MaxStrLen(
                    Projection."Address Office/Apartment"));

        Projection."Address Details" :=
            CopyStr(
                BPAddress."Address Details",
                1,
                MaxStrLen(
                    Projection."Address Details"));
    end;

    local procedure GetCurrentLegalAddress(
        BusinessPartnerNo: Code[60];
        var BPAddress: Record "SI BP Address"): Boolean
    begin
        BPAddress.Reset();

        BPAddress.SetRange(
            "Business Partner No.",
            BusinessPartnerNo);

        BPAddress.SetRange(
            "Address Type",
            BPAddress."Address Type"::Legal);

        if not BPAddress.FindSet() then
            exit(false);

        repeat
            if IsAddressCurrent(BPAddress) then
                exit(true);
        until BPAddress.Next() = 0;

        exit(false);
    end;

    local procedure IsAddressCurrent(
        BPAddress: Record "SI BP Address"): Boolean
    begin
        if (BPAddress."Valid From" <> 0D) and
           (BPAddress."Valid From" > Today())
        then
            exit(false);

        if (BPAddress."Valid To" <> 0D) and
           (BPAddress."Valid To" < Today())
        then
            exit(false);

        exit(true);
    end;

    local procedure ApplyVendorAddress(
        Projection: Record "SI BP ERP Projection";
        var Vendor: Record Vendor)
    begin
        Vendor.Address :=
            CopyStr(
                BuildAddressLine(
                    Projection."Address Street",
                    Projection."Address Building No."),
                1,
                MaxStrLen(Vendor.Address));

        Vendor."Address 2" :=
            CopyStr(
                BuildAddress2Line(
                    Projection."Address Office/Apartment",
                    Projection."Address District"),
                1,
                MaxStrLen(Vendor."Address 2"));

        Vendor.City :=
            CopyStr(
                Projection."Address City",
                1,
                MaxStrLen(Vendor.City));

        Vendor."Post Code" :=
            CopyStr(
                Projection."Address Post Code",
                1,
                MaxStrLen(Vendor."Post Code"));

        Vendor.County :=
            CopyStr(
                Projection."Address Region/State",
                1,
                MaxStrLen(Vendor.County));
    end;

    local procedure ApplyCustomerAddress(
        Projection: Record "SI BP ERP Projection";
        var Customer: Record Customer)
    begin
        Customer.Address :=
            CopyStr(
                BuildAddressLine(
                    Projection."Address Street",
                    Projection."Address Building No."),
                1,
                MaxStrLen(Customer.Address));

        Customer."Address 2" :=
            CopyStr(
                BuildAddress2Line(
                    Projection."Address Office/Apartment",
                    Projection."Address District"),
                1,
                MaxStrLen(Customer."Address 2"));

        Customer.City :=
            CopyStr(
                Projection."Address City",
                1,
                MaxStrLen(Customer.City));

        Customer."Post Code" :=
            CopyStr(
                Projection."Address Post Code",
                1,
                MaxStrLen(Customer."Post Code"));

        Customer.County :=
            CopyStr(
                Projection."Address Region/State",
                1,
                MaxStrLen(Customer.County));
    end;

    local procedure BuildAddressLine(
        Street: Text;
        BuildingNo: Text): Text
    begin
        if Street = '' then
            exit(BuildingNo);

        if BuildingNo = '' then
            exit(Street);

        exit(
            Street + ', ' + BuildingNo);
    end;

    local procedure BuildAddress2Line(
        OfficeApartment: Text;
        District: Text): Text
    var
        Result: Text;
    begin
        if OfficeApartment <> '' then
            Result :=
                'офіс/кв. ' +
                OfficeApartment;

        if District <> '' then begin
            if Result <> '' then
                Result += ', ';

            Result +=
                District;
        end;

        exit(Result);
    end;

    local procedure FillRoleSetup(
        Role: Record "SI BP Role";
        var Projection: Record "SI BP ERP Projection")
    var
        CustSetup: Record "SI BP Cust. Role Setup";
        VendSetup: Record "SI BP Vend. Role Setup";
    begin
        case Role."Role Type" of
            Role."Role Type"::Customer:
                begin
                    CustSetup.Get(
                        Role.Code);

                    Projection."Role Posting Group" :=
                        CustSetup."Customer Posting Group";

                    Projection."Gen. Bus. Posting Group" :=
                        CustSetup."Gen. Bus. Posting Group";

                    Projection."VAT Bus. Posting Group" :=
                        CustSetup."VAT Bus. Posting Group";

                    Projection."Payment Terms Code" :=
                        CustSetup."Payment Terms Code";

                    Projection."Payment Method Code" :=
                        CustSetup."Payment Method Code";

                    Projection."Shipment Method Code" :=
                        CustSetup."Shipment Method Code";

                    Projection."Location Code" :=
                        CustSetup."Location Code";

                    if CustSetup."Currency Code" <> '' then
                        Projection."Currency Code" :=
                            CustSetup."Currency Code";
                end;

            Role."Role Type"::Vendor:
                begin
                    VendSetup.Get(
                        Role.Code);

                    Projection."Role Posting Group" :=
                        VendSetup."Vendor Posting Group";

                    Projection."Gen. Bus. Posting Group" :=
                        VendSetup."Gen. Bus. Posting Group";

                    Projection."VAT Bus. Posting Group" :=
                        VendSetup."VAT Bus. Posting Group";

                    Projection."Payment Terms Code" :=
                        VendSetup."Payment Terms Code";

                    Projection."Payment Method Code" :=
                        VendSetup."Payment Method Code";

                    Projection."Shipment Method Code" :=
                        VendSetup."Shipment Method Code";

                    Projection."Location Code" :=
                        VendSetup."Location Code";

                    if VendSetup."Currency Code" <> '' then
                        Projection."Currency Code" :=
                            VendSetup."Currency Code";
                end;
        end;
    end;

    local procedure CreateBankProjectionLines(
        Role: Record "SI BP Role";
        Projection: Record "SI BP ERP Projection")
    var
        BankAccount: Record "SI BP Bank Account";
        ProjectionBank: Record "SI BP ERP Proj. Bank";
    begin
        BankAccount.SetRange(
            "Role Code",
            Role.Code);

        BankAccount.SetRange(
            Active,
            true);

        BankAccount.SetRange(
            "Verification Status",
            BankAccount."Verification Status"::Verified);

        if not BankAccount.FindSet() then
            exit;

        repeat
            ProjectionBank.Init();

            ProjectionBank."Role Code" :=
                Projection."Role Code";

            ProjectionBank.Code :=
                BankAccount.Code;

            ProjectionBank.IBAN :=
                BankAccount.IBAN;

            ProjectionBank."Account No." :=
                BankAccount."Account No.";

            ProjectionBank."Currency Code" :=
                BankAccount."Currency Code";

            ProjectionBank."Country/Region Code" :=
                BankAccount."Country/Region Code";

            ProjectionBank."Bank Name" :=
                BankAccount."Bank Name";

            ProjectionBank.MFO :=
                BankAccount.MFO;

            ProjectionBank."Bank EDRPOU" :=
                BankAccount."Bank EDRPOU";

            ProjectionBank."Bank Address" :=
                BankAccount."Bank Address";

            ProjectionBank."Bank City" :=
                BankAccount."Bank City";

            ProjectionBank."Bank Postal Code" :=
                BankAccount."Bank Postal Code";

            ProjectionBank."Bank Phone" :=
                BankAccount."Bank Phone";

            ProjectionBank.Primary :=
                BankAccount.Primary;

            ProjectionBank.Insert(true);
        until BankAccount.Next() = 0;
    end;

    local procedure AddError(
        var ErrorText: Text;
        NewError: Text)
    begin
        if ErrorText = '' then
            ErrorText :=
                NewError
        else
            ErrorText :=
                ErrorText + ' ' + NewError;
    end;

    [EventSubscriber(
        ObjectType::Codeunit,
        Codeunit::"SI BP Role Mgt.",
        'OnAfterRoleStatusChanged',
        '',
        false,
        false)]
    local procedure OnAfterRoleStatusChanged(
        var Role: Record "SI BP Role";
        OldStatus: Enum "SI BP Role Status";
        NewStatus: Enum "SI BP Role Status")
    begin
        ApplyMaterializedState(
            Role);
    end;

    local procedure ApplyMaterializedState(
        Role: Record "SI BP Role")
    var
        Projection: Record "SI BP ERP Projection";
        Vendor: Record Vendor;
        Customer: Record Customer;
    begin
        if not Projection.Get(
            Role.Code)
        then
            exit;

        if Projection.Status <>
           Projection.Status::Materialized
        then
            exit;

        case Role."Role Type" of
            Role."Role Type"::Vendor:
                begin
                    if not Vendor.Get(
                        Projection."ERP No.")
                    then
                        exit;

                    case Role.Status of
                        Role.Status::Active:
                            Vendor.Blocked :=
                                Vendor.Blocked::" ";

                        Role.Status::Blocked,
                        Role.Status::Inactive,
                        Role.Status::Closed:
                            Vendor.Blocked :=
                                Vendor.Blocked::All;
                    end;

                    Vendor.Modify(true);
                end;

            Role."Role Type"::Customer:
                begin
                    if not Customer.Get(
                        Projection."ERP No.")
                    then
                        exit;

                    case Role.Status of
                        Role.Status::Active:
                            Customer.Blocked :=
                                Customer.Blocked::" ";

                        Role.Status::Blocked,
                        Role.Status::Inactive,
                        Role.Status::Closed:
                            Customer.Blocked :=
                                Customer.Blocked::All;
                    end;

                    Customer.Modify(true);
                end;
        end;
    end;
}