table 59110 "SI WB Supporting Document"
{
    Caption = 'Супровідний документ вагової';
    DataClassification = CustomerContent;

    fields
    {
        field(1; "Document Entry No."; BigInteger)
        {
            Caption = '№ запису документа';
            TableRelation = "SI Weighbridge Document"."Entry No.";
        }

        field(2; "Line No."; Integer)
        {
            Caption = '№ рядка';
        }

        field(10; "Document Type"; Enum "SI WB Supporting Doc Type")
        {
            Caption = 'Тип документа';
        }

        field(11; "Document No."; Code[50])
        {
            Caption = '№ документа';

            trigger OnValidate()
            begin
                SyncLegacyHeader();
            end;
        }

        field(12; "Document Date"; Date)
        {
            Caption = 'Дата';
        }

        field(13; "File Name"; Text[250])
        {
            Caption = 'Файл';
            Editable = false;
        }

        field(14; Attachment; Blob)
        {
            Caption = 'Вкладення';
        }

        field(15; Note; Text[250])
        {
            Caption = 'Примітка';
        }


        field(20; Generated; Boolean)
        {
            Caption = 'Створено системою';
            Editable = false;
        }

        field(21; "Generated At"; DateTime)
        {
            Caption = 'Створено';
            Editable = false;
        }

        field(22; "Generated By"; Guid)
        {
            Caption = 'Створено користувачем';
            Editable = false;
        }
    }

    keys
    {
        key(PK; "Document Entry No.", "Line No.")
        {
            Clustered = true;
        }

        key(ByType; "Document Entry No.", "Document Type")
        {
        }
    }

    trigger OnInsert()
    begin
        TestField("Document Entry No.");

        if "Document Date" = 0D then
            SetDefaultDate();
    end;

    procedure HasAttachment(): Boolean
    begin
        CalcFields(Attachment);
        exit(Attachment.HasValue());
    end;

    procedure SyncLegacyHeader()
    var
        Header: Record "SI Weighbridge Document";
    begin
        if "Document Entry No." = 0 then
            exit;

        if not Header.Get("Document Entry No.") then
            exit;

        case "Document Type" of
            "SI WB Supporting Doc Type"::TTN:
                Header."TTN No." := "Document No.";

            "SI WB Supporting Doc Type"::"Vendor Delivery Note":
                Header."Vendor Shipment No." := "Document No.";

            "SI WB Supporting Doc Type"::"Delivery Note":
                Header."Delivery Note No." := "Document No.";

            "SI WB Supporting Doc Type"::"Product Passport":
                Header."Product Passport No." := "Document No.";
        end;

        Header.Modify(true);
    end;

    local procedure SetDefaultDate()
    var
        Header: Record "SI Weighbridge Document";
    begin
        if not Header.Get("Document Entry No.") then
            exit;

        if Header."Weighing Date/Time" <> 0DT then
            "Document Date" := DT2Date(Header."Weighing Date/Time");
    end;
}
