table 54060 "SI BP ERP Projection"
{
    Caption = 'ERP-проєкція ролі контрагента';
    DataClassification = CustomerContent;
    DataCaptionFields = "Role Code", "Business Partner Name";

    fields
    {
        field(1; "Role Code"; Code[30])
        {
            Caption = 'Код ролі';
            TableRelation = "SI BP Role".Code;
            NotBlank = true;
        }

        field(2; "Business Partner No."; Code[20])
        {
            Caption = 'Контрагент';
            TableRelation = "SI Business Partner"."No.";
        }

        field(3; "Business Partner Name"; Text[250])
        {
            Caption = 'Назва контрагента';
        }

        field(4; "Role Type"; Enum "SI BP Role Type")
        {
            Caption = 'Тип ролі';
        }

        field(5; Status; Enum "SI BP Projection Status")
        {
            Caption = 'Стан проєкції';
        }

        field(10; Name; Text[250])
        {
            Caption = 'Назва';
        }

        field(11; "Country/Region Code"; Code[10])
        {
            Caption = 'Код країни/регіону';
        }

        field(12; "Currency Code"; Code[10])
        {
            Caption = 'Код валюти';
        }

        field(13; "Registration No."; Text[50])
        {
            Caption = 'Реєстраційний номер';
        }

        field(14; "Tax Registration No."; Text[50])
        {
            Caption = 'Податковий номер';
        }

        field(20; "Role Posting Group"; Code[20])
        {
            Caption = 'Група обліку ролі';
        }

        field(21; "Gen. Bus. Posting Group"; Code[20])
        {
            Caption = 'Бізнес-група обліку';
        }

        field(22; "VAT Bus. Posting Group"; Code[20])
        {
            Caption = 'Бізнес-група ПДВ';
        }

        field(23; "Payment Terms Code"; Code[10])
        {
            Caption = 'Умови оплати';
        }

        field(24; "Payment Method Code"; Code[10])
        {
            Caption = 'Спосіб оплати';
        }

        field(25; "Shipment Method Code"; Code[10])
        {
            Caption = 'Спосіб доставки';
        }

        field(26; "Location Code"; Code[10])
        {
            Caption = 'Код складу';
        }

        field(30; "ERP No."; Code[20])
        {
            Caption = 'Номер в ERP';
            Editable = false;
        }

        field(31; "ERP SystemId"; Guid)
        {
            Caption = 'SystemId ERP';
            Editable = false;
        }

        field(40; "Generated At"; DateTime)
        {
            Caption = 'Створено';
            Editable = false;
        }

        field(41; "Generated By"; Text[100])
        {
            Caption = 'Створив';
            Editable = false;
        }

        field(42; "Validated At"; DateTime)
        {
            Caption = 'Перевірено';
            Editable = false;
        }

        field(43; "Error Message"; Text[2048])
        {
            Caption = 'Помилка';
            Editable = false;
        }

        field(50; "Materialized At"; DateTime)
        {
            Caption = 'Матеріалізовано';
            Editable = false;
        }

        field(51; "Materialized By"; Text[100])
        {
            Caption = 'Матеріалізував';
            Editable = false;
        }

        field(52; "Address Region/State"; Text[100])
        {
            Caption = 'Область/регіон';
        }

        field(53; "Address District"; Text[100])
        {
            Caption = 'Район';
        }

        field(54; "Address City"; Text[100])
        {
            Caption = 'Місто';
        }

        field(55; "Address Post Code"; Code[20])
        {
            Caption = 'Поштовий індекс';
        }

        field(56; "Address Street"; Text[150])
        {
            Caption = 'Вулиця';
        }

        field(57; "Address Building No."; Text[30])
        {
            Caption = 'Номер будинку';
        }

        field(58; "Address Office/Apartment"; Text[30])
        {
            Caption = 'Офіс/квартира';
        }

        field(59; "Address Details"; Text[250])
        {
            Caption = 'Деталі адреси';
        }
    }

    keys
    {
        // Це й забезпечує контракт:
        // одна роль -> максимум одна projection.
        key(PK; "Role Code")
        {
            Clustered = true;
        }
    }

    trigger OnDelete()
    var
        ProjectionBank: Record "SI BP ERP Proj. Bank";
    begin
        if Status = Status::Materialized then
            Error(
                'Матеріалізовану ERP-проєкцію видаляти не можна.');

        ProjectionBank.SetRange(
            "Role Code",
            "Role Code");

        ProjectionBank.DeleteAll(true);
    end;
}